tosca_definitions_version: tosca_simple_yaml_1_3

metadata:
  puccini-js.import.kubernetes.generate: js/generate.js
  puccini-js.import.kubernetes.update: js/update.js

imports:
- artifacts.yaml
- groups.yaml
- policies.yaml
